"""
Все события платформы.

Любой модуль работает НЕ напрямую,
а через события.
"""

# USERS

USER_REGISTERED = "USER_REGISTERED"

STUDENT_REGISTERED = "STUDENT_REGISTERED"

PARENT_REGISTERED = "PARENT_REGISTERED"

TEACHER_REGISTERED = "TEACHER_REGISTERED"

# LESSONS

LESSON_CREATED = "LESSON_CREATED"

LESSON_STARTED = "LESSON_STARTED"

LESSON_FINISHED = "LESSON_FINISHED"

# HOMEWORK

HOMEWORK_CREATED = "HOMEWORK_CREATED"

HOMEWORK_ASSIGNED = "HOMEWORK_ASSIGNED"

HOMEWORK_SUBMITTED = "HOMEWORK_SUBMITTED"

HOMEWORK_CHECKED = "HOMEWORK_CHECKED"

# AI

AI_CHECK_STARTED = "AI_CHECK_STARTED"

AI_CHECK_COMPLETED = "AI_CHECK_COMPLETED"

AI_REPORT_CREATED = "AI_REPORT_CREATED"

AI_MEMORY_UPDATED = "AI_MEMORY_UPDATED"

# REPORTS

PARENT_REPORT_CREATED = "PARENT_REPORT_CREATED"

PARENT_REPORT_SENT = "PARENT_REPORT_SENT"

TEACHER_WEEK_REPORT = "TEACHER_WEEK_REPORT"

# ANALYTICS

PROGRESS_UPDATED = "PROGRESS_UPDATED"

DIAGNOSTIC_COMPLETED = "DIAGNOSTIC_COMPLETED"