from pathlib import Path

p = Path('src/services/ege_exam_service.py')
text = p.read_text(encoding='utf-8')
old = '''def _rate_limit_retry_delay(error: Exception) -> float | None:\n    """Return Gemini's requested delay for a 429, otherwise ``None``."""\n    text = str(error)\n    if "429" not in text and "rate limit" not in text.lower() and "quota" not in text.lower():\n        return None\n    matches = re.findall(r"retry in\\s+([0-9]+(?:\\.[0-9]+)?)s", text, re.IGNORECASE)\n    return min(max(float(matches[-1]) if matches else 60.0, 1.0) + 1.0, 65.0)\n\n\ndef _generate_wording_with_rate_limit_retry(client, **kwargs) -> str:\n    """Retry the same Gemini request after the server-declared quota delay."""\n    for rate_attempt in range(1, 4):\n        try:\n            return client.generate_live_diagnostic_probe(**kwargs)\n        except Exception as error:\n            delay = _rate_limit_retry_delay(error)\n            if delay is None or rate_attempt == 3:\n                raise\n            logger.warning(\n                "Gemini rate limit; retrying same diagnostic request in %.1fs (%s/2)",\n                delay,\n                rate_attempt,\n            )\n            time.sleep(delay)\n    raise RuntimeError("Недостижимая ветка повтора Gemini.")\n'''
new = '''def _is_hard_quota_exhaustion(error: Exception) -> bool:\n    """Return True when retrying the same request cannot restore free-tier quota."""\n    text = str(error).lower()\n    return (\n        "quota exceeded" in text\n        and (\n            "free_tier_requests" in text\n            or "current quota" in text\n            or "plan and billing" in text\n        )\n    )\n\n\ndef _rate_limit_retry_delay(error: Exception) -> float | None:\n    """Return a short retry delay only for a temporary rate-limit window."""\n    if _is_hard_quota_exhaustion(error):\n        return None\n    text = str(error)\n    if "429" not in text and "rate limit" not in text.lower() and "quota" not in text.lower():\n        return None\n    matches = re.findall(r"retry in\\s+([0-9]+(?:\\.[0-9]+)?)s", text, re.IGNORECASE)\n    return min(max(float(matches[-1]) if matches else 60.0, 1.0) + 1.0, 65.0)\n\n\ndef _generate_wording_with_rate_limit_retry(client, **kwargs) -> str:\n    """Retry temporary throttling, but fail fast when the quota itself is exhausted."""\n    for rate_attempt in range(1, 4):\n        try:\n            return client.generate_live_diagnostic_probe(**kwargs)\n        except Exception as error:\n            if _is_hard_quota_exhaustion(error):\n                logger.warning("Gemini quota exhausted; switching to verified local fallback")\n                raise\n            delay = _rate_limit_retry_delay(error)\n            if delay is None or rate_attempt == 3:\n                raise\n            logger.warning(\n                "Gemini rate limit; retrying same diagnostic request in %.1fs (%s/2)",\n                delay,\n                rate_attempt,\n            )\n            time.sleep(delay)\n    raise RuntimeError("Недостижимая ветка повтора Gemini.")\n'''
if old not in text:
    raise SystemExit('rate limit block not found')
text = text.replace(old, new, 1)
old = '''    elif generation.get("status") == "fallback":\n        errors = generation.get("errors") or []\n        detail = f"Причина: {errors[-1]}\\n" if errors else ""\n        source = f"⚠️ Источник: FALLBACK_PROBE\\n{detail}"\n'''
new = '''    elif generation.get("status") == "fallback":\n        source = (\n            "🛡 Проба проверена локально. "\n            "AI-формулировка сейчас недоступна, поэтому использован "\n            "заранее проверенный учебный вариант.\\n"\n        )\n'''
if old not in text:
    raise SystemExit('fallback rendering block not found')
text = text.replace(old, new, 1)
p.write_text(text, encoding='utf-8')

p = Path('tests/test_ege_diagnostics.py')
tests = p.read_text(encoding='utf-8')
addition = r'''\n\ndef test_hard_gemini_quota_exhaustion_is_not_retried():\n    class QuotaClient:\n        def __init__(self):\n            self.calls = 0\n        def generate_live_diagnostic_probe(self, **_kwargs):\n            self.calls += 1\n            raise RuntimeError(\n                "429 quota exceeded for metric generate_content_free_tier_requests; "\n                "please check your current quota, plan and billing details; retry in 55s"\n            )\n\n    client = QuotaClient()\n    try:\n        ege_exam_service._generate_wording_with_rate_limit_retry(client)\n    except RuntimeError:\n        pass\n    else:\n        raise AssertionError("Hard quota exhaustion must propagate to local fallback")\n    assert client.calls == 1\n    assert ege_exam_service._rate_limit_retry_delay(\n        RuntimeError("429 quota exceeded free_tier_requests current quota; retry in 55s")\n    ) is None\n\n\ndef test_fallback_probe_hides_provider_error_from_student():\n    full_map = json.loads(\n        (Path(__file__).parents[1] / "src" / "skills" / "ege_informatics_2026.json").read_text(encoding="utf-8")\n    )\n    attempt = ExamAttempt()\n    case = open_diagnostic_case(5, "wrong", "expected", full_map)\n    case["probe_generation"] = {\n        "status": "fallback",\n        "errors": ["attempt 3: RateLimitError: 429 quota exceeded SECRET_PROVIDER_DETAIL"],\n    }\n    attempt.diagnostics[5] = case\n    ege_exam_service.bind_current_diagnostic_probe(attempt)\n    rendered = ege_exam_service.render_diagnostic_probe(attempt)\n    assert "Проба проверена локально" in rendered\n    assert "AI-формулировка сейчас недоступна" in rendered\n    assert "429" not in rendered\n    assert "RateLimitError" not in rendered\n    assert "SECRET_PROVIDER_DETAIL" not in rendered\n    assert "Причина:" not in rendered\n'''.replace('\\n', '\n')
if 'test_hard_gemini_quota_exhaustion_is_not_retried' not in tests:
    tests += addition
p.write_text(tests, encoding='utf-8')
